import Head from "next/head";

import { About, CTA, Projects } from "@/components";

export default function Home({themeMode, setThemeMode}) {
  return (
    <>
      <Head>
        <title>Junaid Ali Bhatti</title>
        <meta name="Junaid Ali Bhatti" content="Generated by create next app" />
      </Head>

      <CTA themeMode={themeMode} setThemeMode={setThemeMode}/>
      <About themeMode={themeMode} setThemeMode={setThemeMode}/>
      <Projects />

      {/* <TransitionEffect /> */}
    </>
  );
}
